"""The layer that invokes pass-cli and parses its JSON output."""

from pass_tui.cli.auth import SessionInfo, fetch_session, logout
from pass_tui.cli.item import (
    SSH_KEY_TYPES,
    Item,
    ItemDetail,
    ItemField,
    build_create_card_args,
    build_create_login_args,
    build_create_note_args,
    build_create_ssh_key_generate_args,
    build_create_ssh_key_import_args,
    build_update_args,
    create_card_item,
    create_login_item,
    create_note_item,
    create_ssh_key_generate,
    create_ssh_key_import,
    delete_item,
    get_item,
    list_items,
    parse_item_detail,
    update_item_fields,
)
from pass_tui.cli.runner import (
    PASS_CLI_BINARY,
    PassCliError,
    run_pass_cli,
    run_pass_cli_checked,
    run_pass_cli_interactive,
)
from pass_tui.cli.settings import (
    OUTPUT_FORMATS,
    SETTING_DEFAULT_FORMAT,
    SETTING_DEFAULT_VAULT,
    get_setting,
    set_setting,
)
from pass_tui.cli.ssh_agent import (
    SshLoadSummary,
    parse_ssh_load_summary,
    ssh_agent_debug,
    ssh_agent_load,
)
from pass_tui.cli.totp import (
    TOTP_PERIOD,
    get_totp_codes,
    period_index,
    seconds_remaining,
)
from pass_tui.cli.vault import Vault, list_vaults

__all__ = [
    "OUTPUT_FORMATS",
    "PASS_CLI_BINARY",
    "SETTING_DEFAULT_FORMAT",
    "SETTING_DEFAULT_VAULT",
    "SSH_KEY_TYPES",
    "TOTP_PERIOD",
    "Item",
    "ItemDetail",
    "ItemField",
    "PassCliError",
    "SessionInfo",
    "SshLoadSummary",
    "Vault",
    "build_create_card_args",
    "build_create_login_args",
    "build_create_note_args",
    "build_create_ssh_key_generate_args",
    "build_create_ssh_key_import_args",
    "build_update_args",
    "create_card_item",
    "create_login_item",
    "create_note_item",
    "create_ssh_key_generate",
    "create_ssh_key_import",
    "delete_item",
    "fetch_session",
    "get_item",
    "get_setting",
    "get_totp_codes",
    "list_items",
    "list_vaults",
    "logout",
    "parse_item_detail",
    "parse_ssh_load_summary",
    "period_index",
    "seconds_remaining",
    "set_setting",
    "ssh_agent_debug",
    "ssh_agent_load",
    "update_item_fields",
    "run_pass_cli",
    "run_pass_cli_checked",
    "run_pass_cli_interactive",
]
